export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

export const GET_GIVEN_OFFERS = "GET_GIVEN_OFFERS";
export const GET_GIVEN_OFFERS_SUCCESS = "GET_GIVEN_OFFERS_SUCCESS";
export const GET_GIVEN_OFFERS_FAIL = "GET_GIVEN_OFFERS_FAIL";

export const GET_RECEIVED_OFFERS = "GET_RECEIVED_OFFERS";
export const GET_RECEIVED_OFFERS_SUCCESS = "GET_RECEIVED_OFFERS_SUCCESS";
export const GET_RECEIVED_OFFERS_FAIL = "GET_RECEIVED_OFFERS_FAIL";