export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const GET_GIVEN_OFFERS = "GET_GIVEN_OFFERS";
export const GET_GIVEN_OFFERS_SUCCESS = "GET_GIVEN_OFFERS_SUCCESS";
export const GET_GIVEN_OFFERS_FAIL = "GET_GIVEN_OFFERS_FAIL";

export const GET_RECEIVED_OFFERS = "GET_RECEIVED_OFFERS";
export const GET_RECEIVED_OFFERS_SUCCESS = "GET_RECEIVED_OFFERS_SUCCESS";
export const GET_RECEIVED_OFFERS_FAIL = "GET_RECEIVED_OFFERS_FAIL";


export const REJECT_OFFER = "REJECT_OFFER";
export const REJECT_OFFER_SUCCESS = "REJECT_OFFER_SUCCESS";
export const REJECT_OFFER_FAIL = "REJECT_OFFER_FAIL";

export const ACCEPT_OFFER = "ACCEPT_OFFER";
export const ACCEPT_OFFER_SUCCESS = "ACCEPT_OFFER_SUCCESS";
export const ACCEPT_OFFER_FAIL = "ACCEPT_OFFER_FAIL";

export const CANCEL_OFFER = "CANCEL_OFFER";
export const CANCEL_OFFER_SUCCESS = "CANCEL_OFFER_SUCCESS";
export const CANCEL_OFFER_FAIL = "CANCEL_OFFER_FAIL";