export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const PURCHASE_PRODUCT = "PURCHASE_PRODUCT";
export const PURCHASE_PRODUCT_SUCCESS = "PURCHASE_PRODUCT_SUCCESS";
export const PURCHASE_PRODUCT_FAIL = "PURCHASE_PRODUCT_FAIL";

export const OFFER_PRODUCT = "OFFER_PRODUCT";
export const OFFER_PRODUCT_SUCCESS = "OFFER_PRODUCT_SUCCESS";
export const OFFER_PRODUCT_FAIL = "OFFER_PRODUCT_FAIL";