export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const PURCHASE_PRODUCT = "PURCHASE_PRODUCT";
export const PURCHASE_PRODUCT_SUCCESS = "PURCHASE_PRODUCT_SUCCESS";
export const PURCHASE_PRODUCT_FAIL = "PURCHASE_PRODUCT_FAIL";

export const OFFER_PRODUCT = "OFFER_PRODUCT";
export const OFFER_PRODUCT_SUCCESS = "OFFER_PRODUCT_SUCCESS";
export const OFFER_PRODUCT_FAIL = "OFFER_PRODUCT_FAIL";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";

export const GET_ALL_COLOR = "GET_ALL_COLOR";
export const GET_ALL_COLOR_SUCCESS = "GET_ALL_COLOR_SUCCESS";
export const GET_ALL_COLOR_FAIL = "GET_ALL_COLOR_FAIL";

export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const GET_ALL_BRAND_SUCCESS = "GET_ALL_BRAND_SUCCESS";
export const GET_ALL_BRAND_FAIL = "GET_ALL_BRAND_FAIL";

export const GET_ALL_STATUS = "GET_ALL_STATUS";
export const GET_ALL_STATUS_SUCCESS = "GET_ALL_STATUS_SUCCESS";
export const GET_ALL_STATUS_FAIL = "GET_ALL_STATUS_FAIL";